sdk:
  - dev
  - stable
  - 2.17.0

stages:
  - analyze:
      - group:
          - analyze #: --fatal-infos
        sdk: dev
      - group:
          - analyze
        sdk: stable
      - group:
          - analyze
        sdk: 2.17.0
  - build:
      - command: dart run build_runner build --fail-on-severe
  - unit_test:
      - command: dart run build_runner test --fail-on-severe -- -P ci
