sdk:
  - dev
  - stable
  - 2.17.0

stages:
  - analyze:
      # TODO: add --fata-infos once analysis issues have been resolved
      - analyze
  - build:
      - command: dart run build_runner build --fail-on-severe
  - unit_test:
      - command: dart run build_runner test --fail-on-severe -- -P ci
