sdk:
  - dev
  - stable
  - 2.17.0

stages:
  - analyze:
      - group:
          - analyze #: --fatal-infos
        sdk: dev
      - group:
        - analyze
        sdk: stable
  - build:
      - command: dart run build_runner build --fail-on-severe
